export default {
  collection: [{
    literal: 'PRETEST',
    value: 'PRETEST'
  }, {
    literal: 'POSTEST',
    value: 'POSTEST'
  }, {
    literal: 'MAINTENANCE_TEST',
    value: 'MAINTENANCE_TEST'
  }, {
    literal: 'FOLLOW_UP_ONE',
    value: 'FOLLOW_UP_ONE'
  }, {
    literal: 'FOLLOW_UP_TWO',
    value: 'FOLLOW_UP_TWO'
  }],
  sequence: [{
    literal: '01',
    value: 1
  }, {
    literal: '02',
    value: 2
  }, {
    literal: '03',
    value: 3
  }, {
    literal: '04',
    value: 4
  }, {
    literal: '05',
    value: 5
  }, {
    literal: '06',
    value: 6
  }, {
    literal: '07',
    value: 7
  }, {
    literal: '08',
    value: 8
  }, {
    literal: '09',
    value: 9
  }, {
    literal: '10',
    value: 10
  }, {
    literal: '11',
    value: 11
  }, {
    literal: '12',
    value: 12
  }, {
    literal: '13',
    value: 13
  }, {
    literal: '14',
    value: 14
  }, {
    literal: '15',
    value: 15
  }, {
    literal: '16',
    value: 16
  }, {
    literal: '17',
    value: 17
  }, {
    literal: '18',
    value: 18
  }],
  course: [{
    literal: 'COURSE_2',
    value: 'COURSE_2'
  }, {
    literal: 'COURSE_4',
    value: 'COURSE_4'
  }, {
    literal: 'COURSE_8',
    value: 'COURSE_8'
  }]
}
